 
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u212-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      #- image: selenium/standalone-chrome:3.0.1

    working_directory: ~/repo
    steps:
       - checkout
       - run: mkdir test-reports
       - run:
           name: Download Selenium
           command: |
              curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
              curl http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip | gzip -dc > chromedriver
              chmod +x chromedriver
       - run:
           name: Start appium
           command: |
             # java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
             #background: true
              pwd
              #ls
              #cd src && ls
              #cd newpackage && ls && javac MyClass.java
              #cd .. && java newpackage.MyClass
              sudo apt-get install build-essential \
              curl git m4 ruby texinfo libbz2-dev \
              libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev    
              sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
              
              # Add this to end of bashrc
              sudo apt-get install vim
              vim ~/.bashrc

              export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
              export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
              export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"

              # Source bashrc
              source ~.bashrc
              
              brew install gcc
              
              brew update
              brew install node
              brew link node
 
              #no_output_timeout: 30m 