 
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u212-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      #- image: selenium/standalone-chrome:3.0.1

    working_directory: ~/repo
    steps:
       - checkout
       - run: mkdir test-reports
       - run:
           name: Download Selenium
           command: |
              curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
              curl http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip | gzip -dc > chromedriver
              chmod +x chromedriver
       - run:
           name: Start Selenium
           command: |
             # java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
             #background: true
              pwd
              ls
              cd src && ls
              cd newpackage && ls
              javac -cp MyClass.java
              #java MyClass   
              #no_output_timeout: 30m 