 
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u212-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      #- image: selenium/standalone-chrome:3.0.1

    working_directory: ~/repo
    steps:
       - checkout
       - run: mkdir test-reports
       - run:
           name: Download Selenium
           command: |
              curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
              curl http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip | gzip -dc > chromedriver
              chmod +x chromedriver
       - run:
           name: Start appium
           command: |
             # java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
             #background: true
              pwd
              #ls
              #cd src && ls
              #cd newpackage && ls && javac MyClass.java
              #cd .. && java newpackage.MyClass
              
              sudo apt update && sudo apt install nodejs
              sudo apt-get install vim
              sudo apt-get install build-essential \
              curl git m4 ruby texinfo libbz2-dev \
              libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev    
              sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
              
              # Add this to end of bashrc
              
                            
              export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
              export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
              export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
              export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
              export ANDROID_HOME="/home/circleci/repo/android-sdk"
              export PATH=$PATH:$ANDROID_HOME/tools
              export PATH=$PATH:$JAVA_HOME/bin

              source ~/.bashrc
              # Source bashrc
              
                         
              brew install gcc
              
              brew update
              brew install node
              brew link node
              
              #sudo apt update && sudo apt install android-sdk
              
              pwd
              
              cd /usr
              ls               
              cd /lib
              ls
              cd /usr/local/lib
              ls
              
              
              sudo apt-get -y remove default-jdk default-jre default-jdk-headless default-jre-headless ca-certificates-java openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
              sudo rm -rf /usr/local/openjdk-8
              sudo apt-get -y update && sudo apt-get -y install openjdk-8-jdk java-common
              java -version              
              
              npm install appium-doctor -g --unsafe-perm=true --allow-root
                          
              
              appium-doctor
              
              ##sudo apt-get install gradle

              #cd /usr/lib/android-sdk/
              #ls
              cd /home/circleci/repo/
              
              mkdir android-sdk
              cd android-sdk
              pwd 
              ls
              
              sudo wget https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
              sudo unzip sdk-tools-darwin-3859397.zip
              
              ls
              cd tools
              
              
              npm install appium-doctor -g --unsafe-perm=true --allow-root
                          
              
              appium-doctor
              
              #sudo apt install openjdk-8-jdk
              #java -version
              
              sudo $ANDROID_HOME/tools/bin/sdkmanager --list
              
              
              sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-24;google_apis_playstore;x86" 
              sudo $ANDROID_HOME/tools/bin/avdmanager create avd -n nexus -k "system-images;android-24;google_apis_playstore;x86"
              sudo $ANDROID_HOME/tools/bin/avdmanager list avd
                                 
              npm install -g appium@1.14.2 --unsafe-perm=true --allow-root
              npm install wd -g --unsafe-perm=true --allow-root
              
              npm install appium-doctor -g --unsafe-perm=true --allow-root
              
              
              
              appium-doctor
              appium
              
              